# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10
  - name: Research
    url: "research/"
    weight: 20
    identifier: "research"
#  - name: Research interests
#    url: "research-interests/"
    # parent: "research"
#    weight: 30
  - name: Origin of life digest
    url: "research-digest/"
    # parent: "research"
    weight: 40
  - name: Publications
    url: "publications/"
    # parent: "research"
    weight: 30
  - name: Blog
    url: "blog/"
    weight: 100
#  - name: Posts
#    url: '#posts'
#    weight: 20
#  - name: Projects
#    url: '#projects'
#    weight: 30
#  - name: Talks
#    url: '#talks'
#    weight: 40
#  - name: Publications
#    url: '#featured'
#    weight: 50
#  - name: Example
#    url: "example/"
#    weight: 60
#  - name: Contact
#    url: '#contact'
#    weight: 70

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
  - name: CV
    url: uploads/resume.pdf
    weight: 90
